[project]
name = "ComfyUI-FlashVSR"
description = "ComfyUI integration for FlashVSR video super-resolution with VRAM-aware attention backends."
version = "1.3.0"
authors = [
    {name = "naxci1"},
]
maintainers = [
    {name = "DNPMBHC"},
]
license = {file = "LICENSE"} 
classifiers = [
     "Operating System :: OS Independent"
]

[project.urls]
Repository = "https://github.com/DNPMBHC/ComfyUI-FlashVSR"
Documentation = "https://github.com/DNPMBHC/ComfyUI-FlashVSR/blob/main/README.md"
"Bug Tracker" = "https://github.com/DNPMBHC/ComfyUI-FlashVSR/issues"
Forum = "https://github.com/DNPMBHC/ComfyUI-FlashVSR/discussions"

[tool.comfy]
PublisherId = "DNPMBHC"
DisplayName = "ComfyUI-FlashVSR"
Icon = "https://github.com/DNPMBHC/ComfyUI-FlashVSR/raw/main/workflow/logo_tr.png"
includes = []
